package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.ArrayList;
import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.configuration.FieldConstants;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.states.DrivetrainState;
import frc.robot.utilities.GeometryUtil;
import frc.robot.utilities.VisionMeasurement;
import frc.robot.states.ClimbState;
import frc.robot.states.ClimbType;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class Drivetrain extends SubsystemBase {

    private double _maxSpeed = 0.0; // kSpeedAt12Volts desired top
                                    // speed
    private double _maxAngularRate = RotationsPerSecond.of(0.75).in(RadiansPerSecond); // 3/4 of a rotation per second
                                                                                       // max angular velocity
    public ClimbType _currentClimb = ClimbType.IDLE;

    /* Setting up bindings for necessary control of the swerve drive platform */
    private final SwerveRequest.FieldCentric DRIVE = new SwerveRequest.FieldCentric()
            .withDeadband(_maxSpeed * 0.1).withRotationalDeadband(_maxAngularRate * 0.1) // Add a 10% deadband
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage); // Use open-loop control for drive motors
    private final SwerveRequest.SwerveDriveBrake BRAKE = new SwerveRequest.SwerveDriveBrake();
    private final SwerveRequest.PointWheelsAt POINT = new SwerveRequest.PointWheelsAt();
    private final SwerveRequest.ApplyRobotSpeeds CHASSIS_SPEEDS = new SwerveRequest.ApplyRobotSpeeds();

    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    private TunerSwerveDrivetrain _swerve;
    private DrivetrainState _currentState = DrivetrainState.IDLE;
    private final CommandXboxController CONTROLLER;
    private final Vision VISION;
    private double _targetRotation = 0.0;
    private Pose2d _target = new Pose2d();
    private Pose2d _climbTargetStage = new Pose2d();
    private Pose2d _climbTargetEngage = new Pose2d();
    private Pose2d _trenchLeft = new Pose2d();
    private Pose2d _trenchRight = new Pose2d();
    private PIDController _targetFollowControllerX;
    private PIDController _targetFollowControllerY;
    private PIDController _targetFollowControllerZ;
    private double _targetFollowLimit = 0.35;
    private double _xFollow = 0;
    private double _yFollow = 0;

    StructPublisher<Pose2d> publisher = NetworkTableInstance.getDefault()
            .getStructTopic("Robot Pose", Pose2d.struct).publish();
    StructPublisher<Pose2d> targetPosePublisher = NetworkTableInstance.getDefault()
            .getStructTopic("Target Pose", Pose2d.struct).publish();
    private final Field2d m_field;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    public Drivetrain(CommandXboxController controller, Vision vision, boolean isComp) {

        if (isComp) {
            // Use comp bot tuner constants
            _maxSpeed = 1.0 * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond);
            _swerve = TunerConstants.createDrivetrain();
        } else {
            // fix to kitbot later
            _maxSpeed = 1.0 * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond);
            _swerve = TunerConstants.createDrivetrain();
        }

        CONTROLLER = controller;
        VISION = vision;

        _targetFollowControllerX = new PIDController(1.45, 0, 0.04);
        _targetFollowControllerY = new PIDController(1.45, 0, 0.04);
        _targetFollowControllerZ = new PIDController(0.05, 0, 0.002);
        _targetFollowControllerX.setTolerance(.05);
        _targetFollowControllerY.setTolerance(.05);
        _targetFollowControllerZ.setTolerance(2);
        _targetFollowControllerZ.enableContinuousInput(-180, 180);

        m_field = new Field2d();
        SmartDashboard.putData("Field", m_field);

        if (Utils.isSimulation()) {
            startSimThread();
        }

        try {

            // Configure AutoBuilder last
            AutoBuilder.configure(
                    () -> _swerve.getState().Pose, // Get Pose
                    _swerve::resetPose, () -> _swerve.getState().Speeds, // Get Speeds
                    (speeds, feedforwards) -> _swerve.setControl( // Drive
                            CHASSIS_SPEEDS.withSpeeds(speeds)),
                    new PPHolonomicDriveController( // PPHolonomicController is the built in path following controller
                                                    // for
                                                    // holonomic drive trains
                            new PIDConstants(2.5, 0.0, 0.0), // Translation PID constants
                            new PIDConstants(1, 0.0, 0.0) // Rotation PID constants
                    ),
                    RobotConfig.fromGUISettings(), // The robot configuration
                    () -> {
                        // Boolean supplier that controls when the path will be mirrored for the red
                        // alliance
                        // This will flip the path being followed to the red side of the field.
                        // THE ORIGIN WILL REMAIN ON THE BLUE SIDE

                        var alliance = DriverStation.getAlliance();
                        if (alliance.isPresent()) {
                            return alliance.get() == DriverStation.Alliance.Red;
                        }
                        return false;
                    },
                    this // Reference to this subsystem to set requirements
            );
        } catch (Exception exception) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder",
                    exception.getStackTrace());
        }

        setDefaultCommand(idle());
        resetGyro();
    }

    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> _swerve.setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> _swerve.setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        _swerve.setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    public void setWantedClimb(ClimbType wantedClimb) {
        if (wantedClimb != _currentClimb) {
            _currentClimb = wantedClimb;
        }
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        //handleCurrentClimbType();

        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                _swerve.setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }

        updateOdometry();
        updateTarget();
        updateClimbTarget();
        handleCurrentTarget();
        handleCurrentState();
         SmartDashboard.putString("Current State", _currentState.toString());
    }

    private void updateOdometry() {
        ArrayList<VisionMeasurement> visionMeasurements = VISION
                .getVisionMeasurements(
                        _swerve.getPigeon2().getRotation2d().plus(_swerve.getOperatorForwardDirection()));

        _swerve.setVisionMeasurementStdDevs(VecBuilder.fill(.7, .7, Math.PI));
        for (VisionMeasurement visionMeasurement : visionMeasurements) {
            _swerve.addVisionMeasurement(
                    visionMeasurement.pose, Utils.fpgaToCurrentTime(visionMeasurement.timestamp));
        }
        publisher.set(getPose());
        m_field.setRobotPose(getPose());
        m_field.getObject("targetPose").setPose(_target);
        m_field.getObject("climbStagePose").setPose(_climbTargetStage);
        m_field.getObject("climbEngagePose").setPose(_climbTargetEngage);

        SmartDashboard.putString("climbType", _currentClimb.name());
    }

    public double getDistanceToTarget() {
        var distance = _target.getTranslation().getDistance(_swerve.getState().Pose.getTranslation());

        SmartDashboard.putNumber("Distance to Target", distance);
        return distance;
    }

    public void setWantedState(DrivetrainState wantedState) {
        if (wantedState != _currentState) {
            _currentState = wantedState;
        }
    }

    public void setWantedTarget(Translation2d target) {
        _target = new Pose2d(target, new Rotation2d());
    }

    public void setTargetHub(Supplier<Boolean> isRedAlliance) {
        if (isRedAlliance.get()) {
            _target = new Pose2d(FieldConstants.kRedHub, new Rotation2d());
        } else {
            _target = new Pose2d(FieldConstants.kBlueHub, new Rotation2d());
        }
    }

    public void setTargetClimbRight(boolean isRedAlliance) {
        if (isRedAlliance) {
            if (_currentClimb == ClimbType.FRONT) {
                _climbTargetStage = FieldConstants.kRedClimbStageRightFront;
                _climbTargetEngage = FieldConstants.kRedClimbEngageRightFront;
            } else {
                _climbTargetStage = FieldConstants.kRedClimbStageRightSide;
                _climbTargetEngage = FieldConstants.kRedClimbEngageRightSide;

            }
        } else {
            if (_currentClimb == ClimbType.FRONT) {
                _climbTargetStage = FieldConstants.kBlueClimbStageRightFront;
                _climbTargetEngage = FieldConstants.kBlueClimbEngageRightFront;
            } else {
                _climbTargetStage = FieldConstants.kBlueClimbStageRightSide;
                _climbTargetEngage = FieldConstants.kBlueClimbEngageRightSide;
            }
        }
    }

    public void setTargetClimbLeft(boolean isRedAlliance) {
        if (isRedAlliance) {
            if (_currentClimb == ClimbType.FRONT) {
                _climbTargetStage = FieldConstants.kRedClimbStageLeftFront;
                _climbTargetEngage = FieldConstants.kRedClimbEngageLeftFront;
            } else {
                _climbTargetStage = FieldConstants.kRedClimbStageLeftSide;
                _climbTargetEngage = FieldConstants.kRedClimbEngageLeftSide;
            }
        } else {
            if (_currentClimb == ClimbType.FRONT) {
                _climbTargetStage = FieldConstants.kBlueClimbStageLeftFront;
                _climbTargetEngage = FieldConstants.kBlueClimbEngageLeftFront;
            } else {
                _climbTargetStage = FieldConstants.kBlueClimbStageLeftSide;
                _climbTargetEngage = FieldConstants.kBlueClimbEngageLeftSide;
            }
        }
    }

    public void setTargetStageLeftClimb(Supplier<Boolean> isRedAlliance) {

        if (isRedAlliance.get()) {
            if (_currentClimb == ClimbType.FRONT) {
                _target = FieldConstants.kRedClimbStageLeftFront;
            } else {
                _target = FieldConstants.kRedClimbStageLeftSide;
            }
        } else {
            if (_currentClimb == ClimbType.FRONT) {
                _target = FieldConstants.kBlueClimbStageLeftFront;
            } else {
                _target = FieldConstants.kBlueClimbStageLeftSide;
            }
        }
    }

    public void setTargetEngageLeftClimb(Supplier<Boolean> isRedAlliance) {
        if (isRedAlliance.get()) {
            if (_currentClimb == ClimbType.FRONT) {
                _target = FieldConstants.kRedClimbEngageLeftFront;
            } else {
                _target = FieldConstants.kRedClimbEngageLeftSide;
            }
        } else {
            if (_currentClimb == ClimbType.FRONT) {
                _target = FieldConstants.kBlueClimbEngageLeftFront;
            } else {
                _target = FieldConstants.kBlueClimbEngageLeftSide;
            }
        }
    }
    
    public void setTargetDepot(Supplier<Boolean> isRedAlliance) {
        if (isRedAlliance.get()) {
            _target = new Pose2d(FieldConstants.kRedDepot, new Rotation2d());
        } else {
            _target = new Pose2d(FieldConstants.kBlueDepot, new Rotation2d());
        }
    }

    public void setTargetZoneA(Supplier<Boolean> isRedAlliance) {
        if (isRedAlliance.get()) {
            _target = new Pose2d(FieldConstants.kRedZoneA, new Rotation2d());
        } else {
            _target = new Pose2d(FieldConstants.kBlueZoneA, new Rotation2d());
        }
    }

    public void setTargetZoneB(Supplier<Boolean> isRedAlliance) {
        if (isRedAlliance.get()) {
            _target = new Pose2d(FieldConstants.kRedZoneB, new Rotation2d());
        } else {
            _target = new Pose2d(FieldConstants.kBlueZoneB, new Rotation2d());
        }
    }

    public void setTargetLeftTrench(Supplier<Boolean> isRedAlliance) {
        if (isRedAlliance.get()) {
            _trenchRight = FieldConstants.kRightTrench;
        } else {
            _trenchLeft = FieldConstants.kLeftTrench;
        }
    }

    public void setTargetRightTrench(Supplier<Boolean> isRedAlliance) {
        if (isRedAlliance.get()) {
            _trenchLeft = FieldConstants.kLeftTrench;
        } else {
            _trenchRight = FieldConstants.kRightTrench;
        }
    }

    private void updateTarget() {
        if (_currentState != DrivetrainState.CLIMB_ENGAGE && _currentState != DrivetrainState.CLIMB_STAGE || _currentState != DrivetrainState.TRENCH_LEFT || _currentState != DrivetrainState.TRENCH_RIGHT) {
            var currentTranslation = _swerve.getState().Pose.getTranslation();
            if (GeometryUtil.isRedAlliance()) {
                if (currentTranslation.getX() >= 11.3) {
                    setTargetHub(GeometryUtil::isRedAlliance);
                } else {
                    if (currentTranslation.getY() >= 4) {
                        setTargetZoneB(GeometryUtil::isRedAlliance);
                    } else {
                        setTargetZoneA(GeometryUtil::isRedAlliance);
                    }
                }
            } else {
                if (currentTranslation.getX() <= 5.1) {
                    setTargetHub(GeometryUtil::isRedAlliance);
                } else {
                    if (currentTranslation.getY() >= 4) {
                        setTargetZoneA(GeometryUtil::isRedAlliance);
                    } else {
                        setTargetZoneB(GeometryUtil::isRedAlliance);
                    }
                }
            }
        }
    }

    private void updateClimbTarget() {
        var currentTranslation = _swerve.getState().Pose.getTranslation();
        if (GeometryUtil.isRedAlliance()) {
            if (currentTranslation.getY() <= 4.3) {
                setTargetClimbLeft(true);
            } else {
                setTargetClimbRight(true);
            }
        } else {
            if (currentTranslation.getY() >= 3.7) {
                setTargetClimbLeft(false);
            } else {
                setTargetClimbRight(false);
            }
        }
    }

    private void handleCurrentTarget() {

        if (_currentState == DrivetrainState.AIM) {
            var angleToTarget = GeometryUtil.getAngleToTarget(_target.getTranslation(), this::getPose, true);
            _targetFollowControllerZ.setSetpoint(angleToTarget);
        } else if (_currentState == DrivetrainState.CLIMB_STAGE) {
            _targetFollowControllerZ.setSetpoint(_climbTargetStage.getRotation().getDegrees());
        } else if (_currentState == DrivetrainState.CLIMB_ENGAGE) {
            _targetFollowControllerZ.setSetpoint(_climbTargetEngage.getRotation().getDegrees());
        }

        var currentPose = this.getPose();
        _targetRotation = _targetFollowControllerZ.calculate(currentPose.getRotation().getDegrees());

        if (_currentState == DrivetrainState.CLIMB_ENGAGE) {
            _targetFollowControllerX.setSetpoint(_climbTargetEngage.getX());
            _targetFollowControllerY.setSetpoint(_climbTargetEngage.getY());
        } else if (_currentState == DrivetrainState.CLIMB_STAGE) {
            _targetFollowControllerX.setSetpoint(_climbTargetStage.getX());
            _targetFollowControllerY.setSetpoint(_climbTargetStage.getY());
        } else if (_currentState == DrivetrainState.TRENCH_LEFT) {
            _targetFollowControllerY.setSetpoint(_trenchLeft.getY());
        }else if (_currentState == DrivetrainState.TRENCH_RIGHT)  {
            _targetFollowControllerY.setSetpoint(_trenchRight.getY());
        }else {
            _targetFollowControllerX.setSetpoint(_target.getX());
            _targetFollowControllerY.setSetpoint(_target.getY());
        }

        _xFollow = _targetFollowControllerX.calculate(currentPose.getX());
        _yFollow = _targetFollowControllerY.calculate(currentPose.getY());
        _xFollow = MathUtil.clamp(_xFollow, -_targetFollowLimit, _targetFollowLimit);
        _yFollow = MathUtil.clamp(_yFollow, -_targetFollowLimit, _targetFollowLimit);
    }

    private void handleCurrentState() {
        switch (_currentState) {
            case IDLE:
                _swerve.setControl(BRAKE);
                break;
            case OPEN_LOOP:
                _swerve.setControl(
                        DRIVE.withVelocityX(-CONTROLLER.getLeftY() * _maxSpeed) // Drive forward with negative Y
                                                                                // (forward)
                                .withVelocityY(-CONTROLLER.getLeftX() * _maxSpeed) // Drive left with negative X (left)
                                .withRotationalRate(-CONTROLLER.getRightX() * _maxAngularRate)); // Drive
                                                                                                 // counterclockwise
                                                                                                 // with negative X
                                                                                                 // (left)
                break;
            case AIM:
                _swerve.setControl(
                        DRIVE.withVelocityX(-CONTROLLER.getLeftY() * _maxSpeed) // Drive forward with negative Y
                                                                                // (forward)
                                .withVelocityY(-CONTROLLER.getLeftX() * _maxSpeed) // Drive left with negative X (left)
                                .withRotationalRate(_targetRotation * _maxAngularRate) // Drive counterclockwise with
                                                                                       // negative X (left)
                );
                break;
            case CLIMB_STAGE:
            case CLIMB_ENGAGE:
                if (GeometryUtil.isRedAlliance()) {
                    _swerve.setControl(
                            DRIVE.withVelocityX(-_xFollow * _maxSpeed) // Drive forward with negative Y (forward)
                                    .withVelocityY(-_yFollow * _maxSpeed) // Drive left with negative X (left)
                                    .withRotationalRate(_targetRotation * _maxAngularRate) // Drive counterclockwise
                                                                                           // with negative X (left)
                    );
                } else {
                    _swerve.setControl(
                            DRIVE.withVelocityX(_xFollow * _maxSpeed) // Drive forward with negative Y (forward)
                                    .withVelocityY(_yFollow * _maxSpeed) // Drive left with negative X (left)
                                    .withRotationalRate(_targetRotation * _maxAngularRate) // Drive counterclockwise
                                                                                           // with negative X (left)
                    );
                }
                break;
            case TRENCH_LEFT:
            case TRENCH_RIGHT:
                _swerve.setControl(
                    DRIVE.withVelocityX(-CONTROLLER.getLeftY() * _maxSpeed) // Drive forward with negative Y
                    .withVelocityY(_yFollow * _maxSpeed) // Drive left with negative X (left)
                    .withRotationalRate(-CONTROLLER.getRightX() * _maxAngularRate)); 

                                                                                                 
                break;
            case AUTO:
                break;
            default:
                _swerve.setControl(BRAKE);
                break;
        }
    }

    public Pose2d getPose() {
        return _swerve.getStateCopy().Pose;
    }

    public String getCurrentState() {
        return _currentState.toString();
    }

    public boolean isReadyToClimb() {
        // If position is at the ready position
        return _currentState == DrivetrainState.CLIMB_ENGAGE
                && _targetFollowControllerX.atSetpoint()
                && _targetFollowControllerY.atSetpoint()
                && _targetFollowControllerZ.atSetpoint();
    }

    public boolean isStagedForClimb() {
        // If position is at the staged position
        return _currentState == DrivetrainState.CLIMB_STAGE
                && _targetFollowControllerX.atSetpoint()
                && _targetFollowControllerY.atSetpoint()
                && _targetFollowControllerZ.atSetpoint();
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            _swerve.updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    public void resetGyro() {
        _swerve.getPigeon2().setYaw(0);
        _swerve.resetRotation(new Rotation2d());
    }

    public void seedFieldCentric() {
        _swerve.seedFieldCentric();
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return _swerve.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}
